- hosts: "{{ target_hosts | default('all') }}"
  vars:
    target_hosts: app:database
    banner_file: /home/thor/nautilus_banner
  gather_facts: no
  roles:
  - role: app
    become: yes
    action: linux-banner
