- hosts: "{{ task_host }}"
  vars_files:
  - conf/vars.yml
  - conf/vault.yml
  gather_facts: no
  roles:
  - role: app
    become: yes
    action: linux-user-noshell
    action_hint: linux user creation
