- hosts: "{{ target_hosts | default('all') }}"
  vars:
    target_hosts: backup
    repo_name: epel_local
    repo_mount: /packages/downloaded_rpms/
    package: wget
  gather_facts: no
  roles:
  - role: backup
    become: yes
    action: linux-local-yum
