- hosts: app
  vars_files:
    - vars/linux-pam.yml
  gather_facts: no
  roles:
  - role: app
    become: yes
    action: linux-pam

- hosts: balancer
  vars_files:
    - vars/linux-pam.yml
  gather_facts: no
  roles:
  - role: balancer
    become: yes
    action: linux-pam
  