- name: Render protected url
  set_fact:
    test_url: "{{ protected_url | regex_replace('<website-url>:<apache_port>', ansible_host + ':8081') }}"

- name: Test webservice without Basic auth
  uri:
    url: "{{ test_url }}"
    status_code: 401
  vars:
    ansible_connection: local
    ansible_become: no

- name: Test webservice with Basic auth
  uri:
    url: "{{ test_url }}"
    user: "{{ pam_user }}"
    password: "{{ pam_pass }}"
    force_basic_auth: yes
    return_content: yes
  vars:
    ansible_connection: local
    ansible_become: no
  register: resp
  failed_when: "'KodeKloud' not in resp.content"
