- name: Install EPEL repo
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install Apache and Nginx packages
  yum:
    name: ['httpd', 'nginx']
    state: present
    update_cache: yes    

- name: Copy index file to document root
  copy:
    src: "{{ index_file }}"
    dest: /var/www/html/
    mode: 0644
    owner: root
    group: root

- name: Setting Apache port to {{ apache_port }}
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: Listen {{ apache_port }}

- name: Push Nginx configuration
  template:
    src: "{{ action }}.conf.j2"
    dest: /etc/nginx/conf.d/default.conf
    mode: 0640
    owner: root
    group: root

- name: Start and enable httpd and nginx services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop: ['httpd', 'nginx']

- name: Test Apache and Nginx
  uri:
    url: "http://{{ stbkp01.host }}:{{ item }}"
    return_content: yes
  delegate_to: localhost
  register: resp
  failed_when: "'xFusionCorp' not in resp.content"
  loop:
    - "{{ apache_port }}"
    - "{{ nginx_port }}"
