- name: Install Apache and Nginx packages
  yum:
    name: ['epel-release', 'httpd', 'nginx']
    state: present

- name: Start and enable httpd and nginx services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: ['httpd', 'nginx']

- name: Copy index file to document root
  copy:
    src: "{{ index_file }}"
    dest: /var/www/html/

- name: Setting Apache port to {{ apache_port }}
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: Listen {{ apache_port }}
    notify:
      - restart httpd

- name: Push Nginx configuration
  template:
    src: "{{ action }}.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg
    mode: 0640
    owner: root
    group: root
    notify:
      - restart nginx

- name: Test Apache
  uri:
    url: "http://{{ stbkp01.host }}:{{ apache_port }}"
    return_content: yes
  delegate_to: localhost
  register: resp
  failed_when: "'XFusion' not in resp.content"

- name: Test Nginx
  uri:
    url: "http://{{ stbkp01.host }}:{{ nginx_port }}"
    return_content: yes
  delegate_to: localhost
  register: resp
  failed_when: "'XFusion' not in resp.content"
