- name: Copy file to the remote server
  copy:
    src: "{{ source_file }}"
    dest: "{{ destination_dir | regex_replace('/$', '') }}/"
    owner: root
    group: root
    mode: 0644

- name: Remove "{{ source_file }}" on the jump host
  file:
    path: "{{ source_file }}"
    state: absent
  vars:
    ansible_connection: local
    ansible_become: yes
