- name: Install cronie package
  yum:
    name: cronie
    state: present
    update_cache: yes    

- name: Create a Cron Job
  cron:
    name: test
    minute: "{{ minute }}"
    job: "{{ job }}"

- name: Start crond
  service:
    name: crond
    state: started
