- name: Install EPEL repo
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install necessary packages
  yum:
    name: ['mod_authnz_external', 'pwauth']
    state: present
    update_cache: yes

- name: Turn on PAM authentication for protected path
  blockinfile:
    path: /etc/httpd/conf.d/authnz_external.conf
    marker: "{mark}"
    marker_begin: "<Directory \"{{ document_root }}/{{ protected_url | basename }}\">"
    marker_end: "</Directory>"
    block: |2
          AuthType Basic
          AuthName "PAM Authentication"
          AuthBasicProvider external
          AuthExternal pwauth
          require valid-user
    state: present 

- name: Restart httpd service
  service:
    name: httpd
    state: restarted
    enabled: yes

- name: Get Apache config content
  slurp:
    src: /etc/httpd/conf/httpd.conf
  register: httpd_conf
  
- name: Get Apache port from config
  set_fact:
    apache_port: "{{ httpd_conf['content'] | b64decode | regex_search('(?<=\\nListen\\s)[0-9]+') }}"

- name: Render protected url
  set_fact:
    test_url: "{{ protected_url | regex_replace('<website-url>:<apache_port>', ansible_host + ':' + apache_port) }}"

- name: Test webservice without Basic auth
  uri:
    url: "{{ test_url }}"
    status_code: 401
  delegate_to: localhost
  become: no

- name: Test webservice without Basic auth
  uri:
    url: "{{ test_url }}"
    user: "{{ pam_user }}"
    password: "{{ pam_pass }}"
    force_basic_auth: yes
    return_content: yes
  delegate_to: localhost
  become: no
  register: resp
  failed_when: "'KodeKloud' not in resp.content"
